kind: ConfigMap
apiVersion: v1
metadata:
  name: common-config-map
  labels:
    app: services
    app.kubernetes.io/part-of: http-api-example
    app.kubernetes.io/component: frontend
    provider: jkube
    app.openshift.io/runtime: rh-spring-boot
    version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: http-api
    app.openshift.io/runtime-version: 2.3.2.RELEASE
    group: com.workshop.common
data:
  application.properties: >-
    resteasy.jaxrs.defaultPath:/api

    spring.datasource.url=jdbc:mysql://mysql.database-sit.svc.cluster.local:3306/cars

    spring.datasource.username=admin

    spring.datasource.password=password

    spring.jpa.hibernate.ddl-auto=update

    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect

    spring.datasource.testOnBorrow=true 

    spring.datasource.validationQuery=SELECT 1
