---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: services
    provider: jkube
    version: 1.0.0-SNAPSHOT
    group: com.workshop.common
  name: common-config-map
data:
  application.properties: |-
    resteasy.jaxrs.defaultPath:/api

    spring.datasource.url=jdbc:mysql://a65a541ea48824946a99ef3d4d47770b-1928168107.ap-southeast-1.elb.amazonaws.com:3306/cars
    spring.datasource.username=admin
    spring.datasource.password=redhat
    spring.jpa.hibernate.ddl-auto=update

    ## Hibernate Properties
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
    spring.datasource.testOnBorrow=true
    spring.datasource.validationQuery=SELECT 1
