---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: services
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: services@sha256:b22bd68ec2fdec318134353469486b46b47b0ea7f3adea27998af0d7b01bd9bf
        namespace: common
      name: latest
